### ISSUE TITLE
GH-Pages deploys are happening in forks

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-acapy-docs#5]
Is there a way to make gh-pages deploy only happen in the Hyperledger org repository?  I don't think they should be happening in (for example) my fork of the repo.

The deploy is failing in my local repo because of issue #4, but I don't think it should be even trying to be deployed.

**Comment by amanji** [comment]
I think we can restrict the GHA to a specific repo

**Comment by swcurran** [comment]
I probably shouldn't have assigned you that -- others can figure that out.  The first one though -- #4 needs to come from you.
